Bringing in warning fix from facebook's folly.
While working in this space, I noticed that the compiler flags line 703 in conv.h as a warning (and so as an error):

officereact.uwp.0.59.0-vnext.87\inc\folly\conv.h(703) : error C2220: warning treated as error - no 'object' file generated
officereact.uwp.0.59.0-vnext.87\inc\folly\conv.h(703) : warning C4702: unreachable code

while trying to unpack an int using jsArgAsInt(args, 0), likely because the CHECK macro uses an inverse condition on its boolean, and that block of code isn't hittable, since the other 3 enum values already have switch..cases for them? I was able to fix it locally by changing the default to a "case DoubleToStringConverter::PRECISION:" and getting rid of the CHECK call there entirely. This change is just to make the fix more formal at the source of the warning/error by bringing in a part of commit 45ec08480faea02abc087c7ac699ba1b0d404b48 from https://github.com/facebook/folly.